blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/nicotordev/postgresql-mcp-js/discussions
    about: Ask questions and discuss ideas with the community
  - name: MCP Documentation
    url: https://modelcontextprotocol.io/docs
    about: Read the official Model Context Protocol documentation
  - name: Security Issue
    url: https://github.com/nicotordev/postgresql-mcp-js/security/advisories/new
    about: Report a security vulnerability privately
